name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  file:  # id of input
    description: 'directory to file'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'